version: '3.8'

networks:
  traefik_net:
    external: true

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    ports:
      - "85:85"
      - "446:446"
      - "8085:8085"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/config/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/config/acme.json:/acme.json
      - ./traefik/config/users:/etc/traefik/users
    networks:
      - traefik_net

  frontend:
    build: ./portfolio-frontend
    image: portfolio-frontend-25337
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`portfolio.mugabo.rw`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    networks:
      - traefik_net
    depends_on:
      - backend

  backend:
    build: ./portfolio-backend
    image: portfolio-backend-25337
    ports:
    - "3001:3001" 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.portfolio.mugabo.rw`) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.strip-prefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend.middlewares=strip-prefix"
      - "traefik.http.services.backend.loadbalancer.server.port=3001"
    networks:
      - traefik_net
    environment:
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_NAME=portfolio_linux_db
    depends_on:
      - database

  database:
    image: postgres:13
    container_name: portfolio-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: portfolio_linux_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - traefik_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5  
    

volumes:
  postgres_data:
