api:
  dashboard: true
  insecure: false  
  debug: true      

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":446"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "traefik_net"

certificatesResolvers:
  myresolver:
    acme:
      email: andre.mugabo@auca.ac.rw
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory" 
      storage: acme.json
      httpChallenge:
        entryPoint: web
