api:
  dashboard: true
  insecure: true  # For development only

entryPoints:
  web:
    address: ":8080"
  websecure:
    address: ":8444"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "traefik_net"

certificatesResolvers:
  myresolver:
    acme:
      email: andre.mugabo@auca.ac.rw
      storage: acme.json
      httpChallenge:
        entryPoint: web